# Copyright (C) 2004-2005 Masao Mutoh, Laurent Sansonetti 

copyright = <<EOS
# This file is automatically generated by the installer.
# Do not edit by hands.
EOS

File.open('config.rb', 'w') do |file|
    file.print <<EOS

module Booh
    $FPATH = '#{config('data-dir')}/booh'
end
EOS
end

File.open('version.rb', 'w') do |file|
    begin
        version = IO.readlines('../../VERSION').join.chomp
    rescue Errno::ENOENT
        version = "dev"
    end
    file.print <<EOS
# This file is automatically generated by the installer.
# Do not edit by hands.

module Booh
    $VERSION = "#{version}"
end
EOS
end
